spring.application.name=SpringSecurity4
# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN
# Docker DB
spring.datasource.url=jdbc:postgresql://localhost:5432/springbootdb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#create-drop
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
logging.level.org.springframework.boot.autoconfigure=WARN
spring.profiles.active=prod
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR